export * from './guardDom'
export * from './decodeImage'
export * from './getTextSize'
export * from './url2img'
export * from './initConfig'
export * from './drawWatermark'
export * from './observeWatermark'
